trackmate-sc/TrackMate

- pom.xml
- src/main/java/fiji/plugin/trackmate/visualization/trackscheme/SpotIconGrabber.java
- src/main/java/fiji/plugin/trackmate/visualization/trackscheme/SpotImageUpdater.java
- src/main/java/fiji/plugin/trackmate/visualization/trackscheme/TrackScheme.java
TrackScheme acknowledges the radius-ratio setting  when capturing spot thumbnails.
So to get a thumbnail in TrackScheme that has a larger FOV, simply set a larger radius ratio in te GUI 'Configure view' panel and regenerate thumbnails.
> Trackscheme thumbnails

- src/main/java/fiji/plugin/trackmate/action/ExportAllSpotsStatsAction.java
Fixes #75.
See also this forum discussion 
http://forum.imagej.net/t/help-for-bright-spot-detection-with-trackmate-or-process-matching/944
> Add an action that export all visible spots statistics, regardless of whether they belong in a track or not.

- src/main/java/fiji/plugin/trackmate/visualization/TrackMateModelView.java
- src/main/java/fiji/plugin/trackmate/visualization/hyperstack/SpotOverlay.java
- src/main/java/fiji/plugin/trackmate/visualization/hyperstack/TrackOverlay.java
- src/main/java/fiji/plugin/trackmate/visualization/threedviewer/SpotDisplayer3D.java
- src/main/java/fiji/plugin/trackmate/visualization/threedviewer/TrackDisplayNode.java
This track display mode only shows the content of the current selection, for spots and edges. 
It can be accessed in the GUI panel 'Configure views' with a special track display mode called 'Selection only'.
Careful: the content of the selection model can still be edited in this mode.
Of course, the track display mode is ignored by TrackScheme, which then can be used to modify the selection in this mode. 
Fixes  #73.
> New display mode: show only selection.

- src/main/java/fiji/plugin/trackmate/action/CloseGapsByLinearInterpolationAction.java
- src/test/java/fiji/plugin/trackmate/action/CloseGapsByLinearInterpolationActionTest.java
Hey guys,
we wanted to do FRAP analysis. Therefore, it is neccessary to measure the signal of a spot even in frames, when it is not visible. The trackers allow building tracks with gaps, but measurement of the signal in these gaps was not possible. Thus, I introduced the action in this pull request allowing our analysis by introducing new spots in the track at empty frames by interpolating the position before and after the gap. Hopefully it is useful for others.
Cheers,
Robert
> Introducing new Action for closing gaps in tracks

- pom.xml
- src/main/java/fiji/plugin/trackmate/Settings.java
- src/main/java/fiji/plugin/trackmate/TrackMate.java
- src/main/java/fiji/plugin/trackmate/gui/panels/StartDialogPanel.java
If the current ROI is an `ij.gui.ShapeRoi`, we use this to filter the spot detections in each frame. For other cases, we keep the `settings.polygon` for backward compatibility.
See [this discussion](http://forum.imagej.net/t/trackmate-dynamic-filtering-of-spots-after-detection-before-tracking/4246?u=imagejan) on the forum.
> Allow spot detection on images with a discontinuous ShapeRoi

- src/main/java/fiji/plugin/trackmate/TrackModel.java
The nameID in DefaultNameGenerator is initially set to zero, resulting in the duplicated track names occasionally in  the following situations.
-  The MaMuT annotation results containing the tracks with the name pattern of "^Track_[0-9]+$" are opend via MaMuT > Open MaMuT annotation.
- New tracks are generated.
This PR resolves the above issue by setting the nameID to the smallest integer value that is greater than any nameIDs used in the tracks loaded from the annotation file.
> Set the nameID for DefaultNameGenerator on open command

- src/main/java/fiji/plugin/trackmate/action/CaptureOverlayAction.java
- src/main/java/fiji/plugin/trackmate/action/CaptureOverlayPanel.java
The capture overlay action nows only iterate over time, and capture the current channel and Z. 
It also prompts the user for the range they wish to capture.
> Specify range when capture TrackMate overlay.

- .gitignore
- src/main/java/fiji/plugin/trackmate/action/CaptureOverlayAction.java
Especially in scripts.
You can now call a static method like this:
``` java
final TrackMate trackmate = ...
final ImagePlus capture = CaptureOverlayAction.capture( trackmate, 15, 25 );
capture.show();
```
Fixes #142
>  Make the capture-overlay action more usable.

- src/main/java/fiji/plugin/trackmate/action/CopyOverlayAction.java
- src/main/java/fiji/plugin/trackmate/action/ExportAllSpotsStatsAction.java
- src/main/java/fiji/plugin/trackmate/action/ExportStatsToIJAction.java
- src/main/java/fiji/plugin/trackmate/gui/TrackMateGUIController.java
- src/test/java/fiji/plugin/trackmate/interactivetests/ExportStats_TestDrive.java
Upon the selection of a line in any of the 4 tables generated by TrackMate last panel:
- all spots statistics table;
- spots in tracks statistics table;
- links statistics table;
- tracks statistics table,
the corresponding data item gets automatically selected and highlighted:
Commissioned by Pr. Xin Liang,  East China University of Science and Technology.
The reverse direction is NOT implemented (selecting one data item does not highlight it in the table).
> Make the results tables interactive.

- src/main/java/fiji/plugin/trackmate/TrackMate.java
- src/main/java/fiji/plugin/trackmate/TrackMateService.java
- src/main/java/fiji/plugin/trackmate/gui/TrackMateGUIController.java
- src/main/java/fiji/plugin/trackmate/gui/TrackMateWizard.java
- src/main/resources/script_templates/TrackMate/Get_TrackMate_Instance_and_Export_Graph.groovy
This allows scripts to interact with a currently running TrackMate instance by defining a `#@ TrackMate` parameter.
> Add current TrackMate instance to ObjectService

- pom.xml
- src/main/java/fiji/plugin/trackmate/visualization/trackscheme/mxScaledLabelShape.java
And use the groupId sanctioned by the jgraphx developers. This avoids duplicate class conflicts with org.jgrapht:jgrapht-ext, which also depends on jgraphx.
> Update to jgraphx 4.1.0

- src/main/java/fiji/plugin/trackmate/visualization/PerTrackFeatureColorGenerator.java
It was ignored before.
Noticed by @flowman
> Fix setting min & max for PerTrackFeatureColorGenerator.

- src/main/java/fiji/plugin/trackmate/gui/components/LogPanel.java
I was hoping to get access to the entire trackmate log within an Action. In trackmate v7 this isn't possible currently. I was thinking maybe we could just return the entire log when calling toString on the logger. This pattern would seem to follow the situation for the StringBuilderLogger. Just an idea. Feel free to reject if you don't like it.
> resolves #187 LogPanel Logger overrides toString() to return entire log

- src/main/java/fiji/plugin/trackmate/action/MotilityLabExporter.java
MotilityLab is a R application that performs track analysis. One instance is running into a website: http://www.motilitylab.net/startpage.php
The way to import data into the website is to copy-paste a spreadsheet with specified columns in a given order and format.
This action displays the current tracking results in such a spreadsheet, with the columns pre-formatted, so that it can directly copy-pasted in the website without any extra manipulation.
- In the TrackMate table: Ctrl+A, Ctrl+C
- In the MotilityLab import page: Ctrl+V
> An action to export to a MotilityLab spreadsheet.

- src/main/java/fiji/plugin/trackmate/features/spot/SpotContrastAndSNRAnalyzerFactory.java
The priority of this factory is actually _lower_ than that of `SpotIntensityMultiCAnalyzerFactory`, so let's fix the explanation in the javadoc to reflect this.
> SpotContrastAndSNRAnalyzerFactory: adjust javadoc

- src/main/java/fiji/plugin/trackmate/Settings.java
- src/main/java/fiji/plugin/trackmate/TrackMate.java
- src/main/java/fiji/plugin/trackmate/detection/DetectionUtils.java
- src/main/java/fiji/plugin/trackmate/detection/DetectorKeys.java
- src/main/java/fiji/plugin/trackmate/detection/HessianDetector.java
- src/main/java/fiji/plugin/trackmate/detection/HessianDetectorFactory.java
- src/main/java/fiji/plugin/trackmate/detection/LogDetectorFactory.java
- src/main/java/fiji/plugin/trackmate/gui/components/LogPanel.java
- src/main/java/fiji/plugin/trackmate/gui/components/detector/HessianDetectorConfigurationPanel.java
- src/main/java/fiji/plugin/trackmate/gui/wizard/descriptors/ExecuteDetectionDescriptor.java
- src/main/java/fiji/plugin/trackmate/gui/wizard/descriptors/StartDialogDescriptor.java
- src/main/java/fiji/plugin/trackmate/io/TmXmlReader.java
- src/main/java/fiji/plugin/trackmate/io/TmXmlWriter.java
- src/main/java/fiji/plugin/trackmate/util/TMUtils.java
- src/test/java/fiji/plugin/trackmate/detection/HessianDetectorTestDrive1.java
- src/test/java/fiji/plugin/trackmate/detection/HessianDetectorTestDrive2.java
Sometimes one needs to detect bright spots that are not very bright, in a low SNR image, with a lot of unspecific signal:
In the image above, we observe a rather strong non-specific signal in the whole nuclei. The intensity of this non-specific signal versus the background is close to the intensity of the spot signal versus the non-specific signal. Even the nucleus in the image does not look happy about it.
The non-specific signal generates clear and sharp edges at the border of the nucleus, which is picked-up by the LoG detector, with unfortunately a high quality. Our goal is to come up with a better detector, with a better edge response elimination. After some tests I came up with a detector based on the determinant of the Hessian matrix.
The Hessian matrix of an image is a tensor made …
> A new spot detector based on the determinant of Hessian (DoH).

- src/main/java/fiji/plugin/trackmate/features/spot/SpotShapeAnalyzer.java
- src/main/java/fiji/plugin/trackmate/features/spot/SpotShapeAnalyzerFactory.java
This PR introduces a new feature for spots with contour in 2D: the cell shape index 
CSI = Perimeter/√Area
This is kind of redundant with the circularity, but the CSI is an adimensional variable that is used in many papers and studies in  theoretical modelling.
> 'Cell shape index' morphological feature in 2D.

- src/main/java/fiji/plugin/trackmate/action/autonaming/AutoNamingController.java
- src/main/java/fiji/plugin/trackmate/action/closegaps/CloseGapsAction.java
- src/main/java/fiji/plugin/trackmate/action/closegaps/CloseGapsByDetection.java
- src/main/java/fiji/plugin/trackmate/action/closegaps/CloseGapsByLinearInterpolation.java
- src/main/java/fiji/plugin/trackmate/action/closegaps/CloseGapsByLinearInterpolationAction.java
- src/main/java/fiji/plugin/trackmate/action/closegaps/CloseGapsController.java
- src/main/java/fiji/plugin/trackmate/action/closegaps/CloseGapsPanel.java
- src/main/java/fiji/plugin/trackmate/action/closegaps/GapClosingMethod.java
- src/main/java/fiji/plugin/trackmate/gui/components/ActionChooserPanel.java
- src/test/java/fiji/plugin/trackmate/action/CloseGapsByLinearInterpolationActionTest.java
This PR offers a new gap-closing method and the means to add other gap-closing methods in the future.
Gaps are part of tracks where spots are missing in one or several consecutive frames. The gap-closing methods we are offering can introduce new spots in such gaps, depending on possibly the other spots in tracks and/or the image data.
They are useful to fix missed detection when a uninterrupted list of position is required for track analysis. For instance in FRAP experiments, where you need to measure signal intensity changing during time, even if the spot is not visible.
So far TrackMate offered one method to close gaps, developed by @haesleinhuepf. It consists in interpolating the position and radius of missing spots. 
In this PR we introduce a new method that execute a detection …
> Close gaps by detection and new framework for gap-closing methods.

- src/main/java/fiji/plugin/trackmate/visualization/table/BranchTableView.java
Addition of 2 colomns to the Branch Analysis table to give the average time between the analysed branch and the successors (or predecessors) branchs, in case there are gaps in the tracks.
> Addition of average time between a branch and its successors in Branch Analysis action

- src/main/java/fiji/plugin/trackmate/TrackMatePlugIn.java
- src/main/java/fiji/plugin/trackmate/util/TMUtils.java
- src/test/java/fiji/plugin/trackmate/TrackMatePluginTest.java
When started via `TrackMatePlugin`, we add the current `TrackMate` instance to `ObjectService`, so that it's retrievable from scripts.
The replicates the changes from https://github.com/trackmate-sc/TrackMate/pull/153 that got lost with https://github.com/trackmate-sc/TrackMate/commit/0846d838972bf4d96f151231f6447d618c7581a6#diff-43d9484af7470283968294400d50d5898b0d73c5827b532ca8dd81c8579e8b7f.
See also this discussion on zulip:
https://imagesc.zulipchat.com/#narrow/stream/327400-TrackMate/topic/Running.20Trackmate.20within.20napari-imagej
> Register TrackMate with ObjectService

- src/main/java/fiji/plugin/trackmate/Settings.java
- src/main/java/fiji/plugin/trackmate/action/ExportAllSpotsStatsAction.java
- src/main/java/fiji/plugin/trackmate/action/ExportStatsTablesAction.java
- src/main/java/fiji/plugin/trackmate/action/TrackBranchAnalysis.java
- src/main/java/fiji/plugin/trackmate/visualization/table/AllSpotsTableView.java
- src/main/java/fiji/plugin/trackmate/visualization/table/BranchTableView.java
- src/main/java/fiji/plugin/trackmate/visualization/table/TrackTableView.java
- src/test/java/fiji/plugin/trackmate/visualization/table/TrackMateTableExample.java
Change the proposed filename when clicking on "export to csv" from the spot/track/branch table views
The proposed filename is now path_to_image_folder/image_name_"_spots.csv"
> export table filename

- src/main/java/fiji/plugin/trackmate/features/spot/SpotContrastAndSNRAnalyzer.java
- src/main/java/fiji/plugin/trackmate/features/spot/SpotIntensityMultiCAnalyzer.java
> Ignore NaNs in images when computing intensity-related features.

- src/main/java/fiji/plugin/trackmate/action/CTCExporter.java
- src/main/java/fiji/plugin/trackmate/action/LabelImgExporter.java
The float type can accomodate integers at least up to 16M, which is a gig improvement on the 65k limit that we have with unsigned short so far. We could possibly go beyond, but let's see if this is enough.
https://en.wikipedia.org/wiki/Single-precision_floating-point_format#Precision_limitations_on_integer_values
Fix #267
Fix #216
> Export label images on 32-bit float type.

- scripts/ExampleScript_MATLABImportROIs.m
- scripts/ExampleScript_MATLABPlotTracksWithROIs.m
- scripts/trackmateGraph.m
- scripts/trackmateSpots.m
The new `trackmateSpots.m` and `trackmateGraph.m` MATLAB functions do no support the TrackMate files created with v >=7 and can return the 2D polygon that describe the spot contours. 
Fix #257 
Their documentation has been updated.
There are also 2 example scripts, that generate first this:
and the second one makes a movie in MATLAB like this:
https://github.com/trackmate-sc/TrackMate/assets/3583203/a65e7daa-d1bf-4a75-897b-1a50f8a2c5ff
> Fix MATLAB functions - let them import ROIs from TrackMate >= v7

- src/main/java/fiji/plugin/trackmate/io/CSVExporter.java
- src/main/java/fiji/plugin/trackmate/tracking/overlap/OverlapTrackerFactory.java
The CSV export methods in the table classes only exports what is directly shown in the tables, and use the GUI classes of Java. This causes errors when used in a script in a headless model. See the discussion:
https://forum.image.sc/t/error-headlessexception-when-trying-to-save-csv-file-of-tracking-data-from-trackmate-when-running-headlessly/94304/5
This commit adds a utility that exports the content of a model in a headless mode.
This:
```python
CSVExporter.exportSpots( 'trackmate-output.csv', trackmate_model, False );
```
results in:
Fix #288
> Export to CSV file in a headless mode

- src/main/java/fiji/plugin/trackmate/io/TmXmlReader.java
Normally this would cause the reading of the edges and tracks to stop immediatelly.
Now a warning is printed, but the other edges are imported.
> Be more tolerant when loading files with a missing spot.

- pom.xml
- src/main/java/fiji/plugin/trackmate/detection/MaskUtils.java
- src/main/java/fiji/plugin/trackmate/tracking/kdtree/NearestNeighborFlagSearchOnKDTree.java
In particular:
* KDTree implementation was slightly changed: https://github.com/imglib/imglib2/pull/333
* IterableRegion no longer is IterableInterval but has nested `inside()` IterableInterval: https://github.com/imglib/imglib2-roi/pull/71
I would suggest to revisit and merge this when the new ImgLib2 `getType()` API  https://github.com/imglib/imglib2/pull/312 is merged and released
> Fix error wrt changed API in imglib
